// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PageTracker.Infrastructure.Persistence;

#nullable disable

namespace PageTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PageTrackerDbContext))]
    partial class PageTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PageTracker.Domain.Models.ReadingSession", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset>("DateOfSession")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ReadingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
